[package]
name = "mac-notification-sys"
version = "0.6.12"
authors = [
    "Felix Döring <development@felixdoering.com>",
    "Hendrik Sollich <hendrik@hoodie.de>",
]
description = "Thin wrapper around macOS Notifications."
edition = "2024"
rust-version = "1.85"

homepage = "https://github.com/h4llow3En/mac-notification-sys"
repository = "https://github.com/h4llow3En/mac-notification-sys"
documentation = "https://docs.rs/mac-notification-sys/latest/mac_notification_sys/"

license = "MIT/Apache-2.0"
keywords = ["notification", "masOS", "osx", "notify"]
readme = "README.md"

include = ["Cargo.toml", "build.rs", "objc/*", "src/*.rs", "tests/*.rs"]

build = "build.rs"

[package.metadata.docs.rs]
targets = ["aarch64-apple-darwin"]

[dependencies]
objc2-foundation = "0.3"
objc2 = "0.6"
objc2-user-notifications = { version = "0.3", features = [
    "UNNotificationAction",
    "UNNotificationCategory",
    "UNNotificationRequest",
    "UNNotificationResponse",
    "UNNotification",
    "UNUserNotificationCenter",
] }

block2 = "0.6"
time = "0.3"
thiserror = "2.0.18"
futures-lite = "2.6.1"
futures-channel = "0.3.32"
log = "0.4"

[package.metadata.bundle]
name = "mac-notification-sys-example"
identifier = "com.github.h4llow3En.mac-notification-sys.example"
version = "0.1.0"
short_description = "mac-notification-sys example"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
oslog = "0.2"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros"] }
